#!/usr/bin/env sh

# Meant to be sourced by zsh/bash

# Editors
alias n='nano'
alias v='neovim'

# Utilities
[ -x "$(which bat)" ] && alias cat='bat'
alias r='reset'
alias s='ssh'

# Aliases
if [ -x /usr/bin/dircolors ]; then
	alias ls='ls --color=auto'
fi
alias l='ls'
alias la='ls -a'
alias ll='ls -l'

# Git
alias g='git'
alias gs='git status'
alias gb='git branch'
alias gck='git checkout'
alias gcp='git cherry-pick'
alias gl='git log'
alias ga='git add'
alias gc='git commit'
alias gu='git push'
alias gfu='git push --force'
alias gcfg='git config'

# Git rebase
alias grb='git rebase'
alias gra='git rebase --abort'
alias grc='git rebase --continue'

# Git restore
alias gr='git restore'
alias grs='git restore --staged'

# Git submodules
alias gsm='git submodule'
alias gsu='git submodule update'
alias gsi='git submodule init'

# Enable color support of ls and other stuff
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias diff='git diff --no-index -- '
fi

if [ -f "${HOME}/.config/dotfiles/shell/aliases" ]; then
	source "${HOME}/.config/dotfiles/shell/aliases"
fi

export BSP_DIR=""
export LAST_CDBSP_NAME=""

[ -d "/bsp" ] && BSP_DIR="/bsp"
[ -d "/opt/bsp" ] && BSP_DIR="/opt/bsp"
[ -d "/local_build_dir/${USER}/projects" ] && BSP_DIR="/local_build_dir/${USER}/projects"

if [ -d "$BSP_DIR" ]; then
	cdinto() {
		into="$1"; shift 1

		if [ ! -d "$BSP_DIR" ]; then
			echo "No BSP directory!"
			return 1
		fi

		if [ -z "LAST_CDBSP_NAME" ]; then
			echo -e "\e[1;33mDefaulting to main\e[0m"
			export LAST_CDBSP_NAME="main"
		fi

		cd "${BSP_DIR}/${LAST_CDBSP_NAME}/${into}"
	}

	cdbsp() {
		cdinto "jlbsp" "$@"
	}
	cdbds() {
		cdinto "builds" "$@"
	}
fi
