#!/usr/bin/env bash

# Source distro information
if [ -f /etc/os-release ]; then
	source /etc/os-release
else
	echo "Could not detect Linux distribution."
	exit 1
fi

pkgs=("ripgrep" "fzf" "zsh" "nano" "tmux" "htop" "btop" "nmap" "iperf" "git" "net-tools")
pkgs_apt=("fd-find")
pkgs_pac=("fd" "eza")

if [ -n "$XDG_SESSION_ID" ]; then
	echo "We're on a desktop machine, installing desktop packages as well!"
	pkgs+=("firefox-esr" "kate" "kitty")
fi

# Switch case on distro ID
case "$ID" in
	debian)
		echo -e "\e[1;33mDebian detected, Installing packages using apt\e[0m"
		echo sudo apt install -y "${pkgs[@]}" "${pkgs_apt[@]}"
		sudo apt install -y "${pkgs[@]}" "${pkgs_apt[@]}"
		;;
	arch)
		echo -e "\e[1;33mArch linux detected, Installing packages using pacman\e[0m"
		echo sudo pacman --noconfirm -S "${pkgs[@]}" "${pkgs_pac[@]}"
		sudo pacman --noconfirm -S "${pkgs[@]}" "${pkgs_pac[@]}"
		;;
	*)
		echo "Unknown distribution: $ID"
		;;
esac

# Check if we're on our own subnet or not
if ip addr show | grep -qP '^\s+inet\s+192\.168\.[0-7]?\.[0-9]{1,3}\/21'; then
	echo "We're on our own subnet!"
fi

