#!/usr/bin/env bash

set -eo pipefail

SRC_PATH="$(realpath "${BASH_SOURCE[0]}")"
DOTFILES_STAMP="$HOME/.dotfiles_installed"

SKIP_BACKUP=0
if [ -e "$DOTFILES_STAMP" ]; then
	echo -e "\e[1;33mDotfiles are already installed, not backing anything up!\e[0m"
	SKIP_BACKUP=1
fi

export DOTFILES_PATH="$(dirname "$SRC_PATH")"
echo -e "\e[1;33mSetting up dotfiles in ${DOTFILES_PATH}!\e[0m"

back_df() {
	if [ $SKIP_BACKUP -eq 0 ]; then
		if [ -f "$1" ]; then
			if [ -f "$1.bak" ]; then
				echo -e "\e[1;31mBackup file (${1}.bak) already exists, please delete or rename!\e[0m"
				exit 1
			else
				mv "$1" "${1}.bak"
				echo -e "\e[1;33mDotfile $1 already esists, backed up to ${1}.bak!\e[0m"
			fi
		fi
	fi
}
link_df() {
	rp1="$(realpath "$1")"
	rp2="$(realpath "$2")"
	if [ -h "$1" ] && [ "$rp1" == "$rp2" ]; then
		echo -e "\e[1;32mDotfile \"$1\" already linked, not doing anything!\e[0m"
		return 0
	fi

	back_df "$1"
	if [ -n "$2" ]; then
		ln -s "$2" "$1"
		echo -e "\e[1;32mSymlink created for $2\e[0m"
	fi
}

link_df "$HOME/.zshrc"  "$DOTFILES_PATH/zshrc"
link_df "$HOME/.bashrc" "$DOTFILES_PATH/bashrc"
back_df "$HOME/.nanorc"

cat "$DOTFILES_PATH/nanorc" | envsubst >"$HOME/.nanorc"
echo -e "\e[1;32mCreated nanorc via envsubst\e[0m"

echo -e "\e[1;32mDotfiles create successfully!\e[0m"
touch "$DOTFILES_STAMP"
