set -g mouse on
# bind-key / copy-mode \; send-key ?
set -g history-limit 50000

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set-hook -g session-created 'run-shell "${DOTFILES_PATH}/tmux-powerline/powerline.sh init"'

set -g status on
set -g status-interval 2
set -g status-justify "centre"
set -g status-left-length 60
set -g status-right-length 90
set -g status-style fg=white,bg=#222222
set -g status-left "#(${DOTFILES_PATH}/tmux-powerline/powerline.sh left)"
set -g status-right "#(${DOTFILES_PATH}/tmux-powerline/powerline.sh right)"
